### ISSUE TITLE
Further development of idea

### ISSUE THREAD

**Issue by freealise** [jacopocolo/Penzil#21]
Would it be more usable if the flat canvas was moved in multitouch, simultaneously with drawing?
Or you might consider the approach of [Feather](https://feather.art) - first making a curved surface then lines on it.

**Comment by jacopocolo** [comment]
Hi! A previous version of Penzil had multitouch for moving the canvas but I felt that it was too cumbersome and slow. So I switched to the approach you see today.

Regarding a curved canvas: development of Penzil is on pause right now but I'll consider it if/when I start working on Penzil again. Thanks!

**Comment by freealise** [comment]
A sprite makes a decent canvas, at least I couldn't have done better.

**Comment by freealise** [comment]
If you're at all interested, I managed to get rid of the canvas altogether and get to drawing with transform controls (only in the voxel painter). Learning threejs somehow >.<

**Comment by jacopocolo** [comment]
@freealise that's cool! Did you integrate Penzil with this [voxel painter](https://threejs.org/examples/webgl_interactive_voxelpainter.html)?

**Comment by freealise** [comment]
Yes, certainly that example - although the story has been long and dramatic :)

I intended to fork Penzil, but don't understand Vue and not interested - while I am a front-end developer, reasonable defaults like lil-gui are ok with me, as interface design is too much of a struggle to get into.

The meshline and tubegeometry with variable width looked useful, but the former doesn't behave right with shadows and the latter is heavier, so I tried to make the whole object out of a few tubes and got confused.

Then I replaced the tube with extrudegeometry as an attempt to draw [across the form](https://raw.githubusercontent.com/spite/THREE.MeshLine/master/screenshots/shape.jpg) instead of along it, to reduce it to simple shapes (I'm not good at drawing either), but most people wouldn't think of it like that.

Voxels initially got rejected as they're not easily rotated (it's meant for animation), but a nurbs curve or surface runs nicely through the boxy control points selected on the drawing, and so it became the solution.

So it ended up more of an inspiration than integration, just the basic idea.

**Comment by freealise** [comment]
Hello again,
I actually managed to get to a result that might be an improvement of your app ([here](https://freeali.se/svox)) - but failed to get it to be useful for animation, so it has lost its point for me. Being hopelessly bad as an interface designer and with all things visual, I will not continue with Three.js by myself - so consider it a Halloween gift in public domain :)

It is a raster painting interface. The textarea on the right is for [Smooth Voxels](https://svox.glitch.me) - I see that it's awkward, but there's possibly a way for this to be done without the dependency (if I manage to).

![Screenshot 2023-10-10 at 08 32 48](https://github.com/webspace-sdk/smoothvoxels/assets/5275747/6024f561-e267-4595-9459-138045418b0e)
